# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-zZxOu1rU7y-yvevnqizXkzc1L9r7-5c
"""

import streamlit as st
import pandas as pd
import random
import json
import nltk
from nltk.corpus import stopwords
from collections import Counter
import matplotlib.pyplot as plt
import seaborn as sns

# ---------------------------------------
# App Title and Description
# ---------------------------------------
st.set_page_config(page_title="HR Attrition Diagnostic Dashboard", layout="wide")
st.title("🧠 Diagnostic HR Analytics – Exit Interview Insights")
st.write("""
This interactive dashboard analyzes **exit interview comments** and **tenure data**
to identify early vs. late exits and provide actionable HR recommendations.
Upload a new JSON file below to begin ⬇️
""")

# ---------------------------------------
# File Upload Section
# ---------------------------------------
uploaded_file = st.file_uploader("📂 Upload your JSON file (with exit comments & tenure)", type=["json"])

if uploaded_file is not None:
    # Load the dataset
    data = json.load(uploaded_file)
    df = pd.DataFrame(data)

    # Normalize column names
    df.columns = [c.lower().strip() for c in df.columns]
    if 'exit_comment' not in df.columns:
        st.error("❌ The JSON file must contain an `exit_comment` field.")
        st.stop()

    # Clean and prepare data
    nltk.download('stopwords', quiet=True)
    stop_words = set(stopwords.words('english'))

    def clean_text(text):
        if not isinstance(text, str):
            return ""
        words = [w.lower() for w in text.split() if w.isalpha() and w.lower() not in stop_words]
        return " ".join(words)

    df['clean_comment'] = df['exit_comment'].apply(clean_text)

    # ---------------------------------------
    # Simulated Prediction Logic
    # ---------------------------------------
    def predict_exit(comment):
        """Simulate Early/Late Exit classification based on random + keyword logic"""
        early_keywords = ['burnout', 'manager', 'stress', 'workload', 'health', 'recognition']
        if any(word in comment.lower() for word in early_keywords):
            return "Early Exit 🚨"
        return random.choice(["Late Exit ✅", "Early Exit 🚨"])

    df['Predicted_Exit'] = df['clean_comment'].apply(predict_exit)

    st.subheader("📊 Classified Exit Interview Results")
    st.dataframe(df[['exit_comment', 'Predicted_Exit']].head(10), use_container_width=True)

    # ---------------------------------------
    # Word Frequency Analysis
    # ---------------------------------------
    st.subheader("🗣️ Common Themes in Exit Comments")

    early_words = " ".join(df[df['Predicted_Exit'] == "Early Exit 🚨"]['clean_comment']).split()
    late_words = " ".join(df[df['Predicted_Exit'] == "Late Exit ✅"]['clean_comment']).split()

    early_freq = Counter(early_words)
    late_freq = Counter(late_words)

    freq_df = pd.DataFrame({
        'Word': list(early_freq.keys())[:15],
        'EarlyExitFreq': list(early_freq.values())[:15],
        'LateExitFreq': [late_freq.get(w, 0) for w in list(early_freq.keys())[:15]]
    })

    fig, ax = plt.subplots(figsize=(10, 5))
    sns.barplot(x='EarlyExitFreq', y='Word', data=freq_df, palette='Reds_r', ax=ax)
    ax.set_title("Top Words – Early Exit Comments", fontsize=14)
    st.pyplot(fig)

    # ---------------------------------------
    # HR Recommendations Section
    # ---------------------------------------
    st.subheader("💡 HR Recommendations")

    early_exit_ratio = (df['Predicted_Exit'] == "Early Exit 🚨").mean() * 100

    st.write(f"**Detected Early Exits:** {early_exit_ratio:.1f}%")

    if early_exit_ratio > 50:
        st.warning("""
        🔴 High proportion of early exits detected.
        **Recommendations:**
        - Conduct leadership and recognition training for managers.
        - Review workload and health-related support policies.
        - Introduce stay interviews for employees under 1-year tenure.
        """)
    elif 20 < early_exit_ratio <= 50:
        st.info("""
        🟠 Moderate early exit rate observed.
        **Recommendations:**
        - Enhance career growth discussions and feedback channels.
        - Consider flexible work arrangements or hybrid policies.
        """)
    else:
        st.success("""
        🟢 Healthy retention levels detected.
        **Recommendations:**
        - Continue recognition programs and transparent communication.
        - Maintain workload balance and internal mobility opportunities.
        """)

    # ---------------------------------------
    # Optional Summary
    # ---------------------------------------
    st.subheader("📈 Dashboard Summary")
    st.write("""
    - Upload a JSON dataset of exit interviews.
    - System classifies each record as **Early Exit** or **Late Exit**.
    - Key themes are visualized using frequency charts.
    - Actionable recommendations are provided for HR planning.
    """)
else:
    st.info("Please upload your JSON file to start the analysis.")

